# Generated by Django 4.1.7 on 2023-04-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Session_year',
        ),
    ]
